version: '3.3'
services:
  mailhog-keycloak:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - keycloak_users_network

  keycloak-certify:
    image: quay.io/keycloak/keycloak:11.0.3
    container_name: keycloak-certify
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      JAVA_OPTS: '-Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/certify-export2.json -Dkeycloak.migration.strategy=IGNORE_EXISTING'
    ports:
      - 8080:8080
    volumes:
      - './keycloak/realms:/tmp'
    networks:
      - keycloak_users_network

  keycloak-device:
    image: quay.io/keycloak/keycloak:11.0.3
    container_name: keycloak-device
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      JAVA_OPTS: '-Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/device-export.json -Dkeycloak.migration.strategy=IGNORE_EXISTING'
    ports:
      - 8081:8080
    volumes:
      - './keycloak/realms:/tmp'
    networks:
      - keycloak_device_network

  postgres:
    image: postgres:13.2
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - db_network

  flyway:
    container_name: flyway
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/postgres
    image: flyway/flyway:7.8.1
    command: -connectRetries=60 migrate
    networks:
      - db_network
    volumes:
      - $PWD/src/main/resources/db/migration:/flyway/sql
      - $PWD/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      - postgres

  teamdrive:
    image: teamdrive/agent:latest
    restart: unless-stopped
    ports:
      - 4040:4040

networks:
  db_network:
  keycloak_users_network:
  keycloak_device_network:
